version: '3.1'

services:
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"  # MySQL will be available on localhost:3307
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changemeinprod!
      MYSQL_DATABASE: springBoot_project  # Ensures the database is created
